/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: krml -skip-linking -skip-compilation -tmpdir extracted -bundle HTTP.Extract.Types=HTTP.Extract.Types -bundle HTTP.Extract.Scan=HTTP.Extract.Scan -bundle HTTP.Extract.Method=HTTP.Extract.Method -bundle HTTP.Extract.Path=HTTP.Extract.Path -bundle HTTP.Extract.Header=HTTP.Extract.Header -bundle HTTP.Extract.Bearer=HTTP.Extract.Bearer -bundle HTTP.Extract.Complete=HTTP.Extract.Complete -bundle IPC.Extract=IPC.Extract -no-prefix HTTP.Extract.Types -no-prefix HTTP.Extract.Scan -no-prefix HTTP.Extract.Method -no-prefix HTTP.Extract.Path -no-prefix HTTP.Extract.Header -no-prefix HTTP.Extract.Bearer -no-prefix HTTP.Extract.Complete -no-prefix IPC.Extract .extract/out.krml
  F* version: <unknown>
  KaRaMeL version: <unknown>
 */

#include "HTTP_Extract_Header.h"

uint32_t parse_digits(uint8_t *buf, uint32_t header_end, uint32_t j, uint32_t acc)
{
  if (j == header_end)
    return acc;
  else
  {
    uint8_t b = buf[j];
    if (b >= 0x30U && b <= 0x39U)
    {
      uint32_t digit = (uint32_t)((uint32_t)b - 0x30U);
      uint32_t new_acc = acc * 10U + digit;
      if (new_acc > 1361U)
        return 1362U;
      else
        return parse_digits(buf, header_end, j + 1U, new_acc);
    }
    else
      return acc;
  }
}

uint32_t skip_spaces(uint8_t *buf, uint32_t header_end, uint32_t j)
{
  if (j == header_end)
    return j;
  else
  {
    uint8_t b = buf[j];
    if (b == 0x20U)
      return skip_spaces(buf, header_end, j + 1U);
    else
      return j;
  }
}

bool check_content_length_upper(uint8_t *buf, uint32_t h)
{
  uint8_t b0 = buf[h];
  uint8_t b1 = buf[h + 1U];
  uint8_t b2 = buf[h + 2U];
  uint8_t b3 = buf[h + 3U];
  uint8_t b4 = buf[h + 4U];
  uint8_t b5 = buf[h + 5U];
  uint8_t b6 = buf[h + 6U];
  uint8_t b7 = buf[h + 7U];
  uint8_t b8 = buf[h + 8U];
  uint8_t b9 = buf[h + 9U];
  uint8_t b10 = buf[h + 10U];
  uint8_t b11 = buf[h + 11U];
  uint8_t b12 = buf[h + 12U];
  uint8_t b13 = buf[h + 13U];
  uint8_t b14 = buf[h + 14U];
  return
    b0 == 0x43U && b1 == 0x6FU && b2 == 0x6EU && b3 == 0x74U && b4 == 0x65U && b5 == 0x6EU &&
      b6 == 0x74U
    && b7 == 0x2DU
    && b8 == 0x4CU
    && b9 == 0x65U
    && b10 == 0x6EU
    && b11 == 0x67U
    && b12 == 0x74U
    && b13 == 0x68U
    && b14 == 0x3AU;
}

bool check_content_length_lower(uint8_t *buf, uint32_t h)
{
  uint8_t b0 = buf[h];
  uint8_t b1 = buf[h + 1U];
  uint8_t b2 = buf[h + 2U];
  uint8_t b3 = buf[h + 3U];
  uint8_t b4 = buf[h + 4U];
  uint8_t b5 = buf[h + 5U];
  uint8_t b6 = buf[h + 6U];
  uint8_t b7 = buf[h + 7U];
  uint8_t b8 = buf[h + 8U];
  uint8_t b9 = buf[h + 9U];
  uint8_t b10 = buf[h + 10U];
  uint8_t b11 = buf[h + 11U];
  uint8_t b12 = buf[h + 12U];
  uint8_t b13 = buf[h + 13U];
  uint8_t b14 = buf[h + 14U];
  return
    b0 == 0x63U && b1 == 0x6FU && b2 == 0x6EU && b3 == 0x74U && b4 == 0x65U && b5 == 0x6EU &&
      b6 == 0x74U
    && b7 == 0x2DU
    && b8 == 0x6CU
    && b9 == 0x65U
    && b10 == 0x6EU
    && b11 == 0x67U
    && b12 == 0x74U
    && b13 == 0x68U
    && b14 == 0x3AU;
}

uint32_t scan_for_content_length(uint8_t *buf, uint32_t header_end, uint32_t i)
{
  if (header_end - i < 17U)
    return 0U;
  else
  {
    uint8_t b0 = buf[i];
    uint8_t b1 = buf[i + 1U];
    if (b0 == 0x0DU && b1 == 0x0AU)
    {
      uint32_t h = i + 2U;
      if (h + 15U <= header_end)
      {
        bool is_upper = check_content_length_upper(buf, h);
        bool is_lower = check_content_length_lower(buf, h);
        if (is_upper || is_lower)
        {
          uint32_t val_start = h + 15U;
          uint32_t val_start_ = skip_spaces(buf, header_end, val_start);
          return parse_digits(buf, header_end, val_start_, 0U);
        }
        else
          return scan_for_content_length(buf, header_end, i + 1U);
      }
      else
        return 0U;
    }
    else
      return scan_for_content_length(buf, header_end, i + 1U);
  }
}

uint32_t parse_content_length(uint8_t *buf, uint32_t header_end)
{
  return scan_for_content_length(buf, header_end, 0U);
}

