/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: krml -skip-linking -skip-compilation -tmpdir extracted -bundle HTTP.Extract.Types=HTTP.Extract.Types -bundle HTTP.Extract.Scan=HTTP.Extract.Scan -bundle HTTP.Extract.Method=HTTP.Extract.Method -bundle HTTP.Extract.Path=HTTP.Extract.Path -bundle HTTP.Extract.Header=HTTP.Extract.Header -bundle HTTP.Extract.Bearer=HTTP.Extract.Bearer -bundle HTTP.Extract.Complete=HTTP.Extract.Complete -bundle IPC.Extract=IPC.Extract -no-prefix HTTP.Extract.Types -no-prefix HTTP.Extract.Scan -no-prefix HTTP.Extract.Method -no-prefix HTTP.Extract.Path -no-prefix HTTP.Extract.Header -no-prefix HTTP.Extract.Bearer -no-prefix HTTP.Extract.Complete -no-prefix IPC.Extract .extract/out.krml
  F* version: <unknown>
  KaRaMeL version: <unknown>
 */

#include "HTTP_Extract_Path.h"

#include "HTTP_Extract_Types.h"

uint32_t find_path_end(uint8_t *buf, uint32_t limit, uint32_t i)
{
  if (i == limit)
    return i;
  else
  {
    uint8_t b = buf[i];
    if (b == 0x20U || b == 0x3FU || b == 0x0DU)
      return i;
    else
      return find_path_end(buf, limit, i + 1U);
  }
}

bool check_no_traversal(uint8_t *buf, uint32_t path_start, uint32_t path_end, uint32_t i)
{
  if (path_end - i < 2U)
    return true;
  else
  {
    uint8_t b0 = buf[i];
    uint8_t b1 = buf[i + 1U];
    if (b0 == 0x2EU && b1 == 0x2EU)
      return false;
    else
      return check_no_traversal(buf, path_start, path_end, i + 1U);
  }
}

bool check_no_null(uint8_t *buf, uint32_t path_end, uint32_t i)
{
  if (i == path_end)
    return true;
  else
  {
    uint8_t b = buf[i];
    if (b == 0x00U)
      return false;
    else
      return check_no_null(buf, path_end, i + 1U);
  }
}

bool is_root_path(uint8_t *buf, uint32_t path_start, uint32_t path_end)
{
  uint32_t path_len = path_end - path_start;
  if (path_len == 1U)
  {
    uint8_t b = buf[path_start];
    return b == 0x2FU;
  }
  else
    return false;
}

bool is_path_login(uint8_t *buf, uint32_t ps)
{
  uint8_t b0 = buf[ps];
  uint8_t b1 = buf[ps + 1U];
  uint8_t b2 = buf[ps + 2U];
  uint8_t b3 = buf[ps + 3U];
  uint8_t b4 = buf[ps + 4U];
  uint8_t b5 = buf[ps + 5U];
  uint8_t b6 = buf[ps + 6U];
  uint8_t b7 = buf[ps + 7U];
  uint8_t b8 = buf[ps + 8U];
  uint8_t b9 = buf[ps + 9U];
  return
    b0 == 0x2FU && b1 == 0x61U && b2 == 0x70U && b3 == 0x69U && b4 == 0x2FU && b5 == 0x6CU &&
      b6 == 0x6FU
    && b7 == 0x67U
    && b8 == 0x69U
    && b9 == 0x6EU;
}

bool is_path_logout(uint8_t *buf, uint32_t ps)
{
  uint8_t b0 = buf[ps];
  uint8_t b1 = buf[ps + 1U];
  uint8_t b2 = buf[ps + 2U];
  uint8_t b3 = buf[ps + 3U];
  uint8_t b4 = buf[ps + 4U];
  uint8_t b5 = buf[ps + 5U];
  uint8_t b6 = buf[ps + 6U];
  uint8_t b7 = buf[ps + 7U];
  uint8_t b8 = buf[ps + 8U];
  uint8_t b9 = buf[ps + 9U];
  uint8_t b10 = buf[ps + 10U];
  return
    b0 == 0x2FU && b1 == 0x61U && b2 == 0x70U && b3 == 0x69U && b4 == 0x2FU && b5 == 0x6CU &&
      b6 == 0x6FU
    && b7 == 0x67U
    && b8 == 0x6FU
    && b9 == 0x75U
    && b10 == 0x74U;
}

bool is_path_status(uint8_t *buf, uint32_t ps)
{
  uint8_t b0 = buf[ps];
  uint8_t b1 = buf[ps + 1U];
  uint8_t b2 = buf[ps + 2U];
  uint8_t b3 = buf[ps + 3U];
  uint8_t b4 = buf[ps + 4U];
  uint8_t b5 = buf[ps + 5U];
  uint8_t b6 = buf[ps + 6U];
  uint8_t b7 = buf[ps + 7U];
  uint8_t b8 = buf[ps + 8U];
  uint8_t b9 = buf[ps + 9U];
  uint8_t b10 = buf[ps + 10U];
  return
    b0 == 0x2FU && b1 == 0x61U && b2 == 0x70U && b3 == 0x69U && b4 == 0x2FU && b5 == 0x73U &&
      b6 == 0x74U
    && b7 == 0x61U
    && b8 == 0x74U
    && b9 == 0x75U
    && b10 == 0x73U;
}

bool is_path_policy(uint8_t *buf, uint32_t ps)
{
  uint8_t b0 = buf[ps];
  uint8_t b1 = buf[ps + 1U];
  uint8_t b2 = buf[ps + 2U];
  uint8_t b3 = buf[ps + 3U];
  uint8_t b4 = buf[ps + 4U];
  uint8_t b5 = buf[ps + 5U];
  uint8_t b6 = buf[ps + 6U];
  uint8_t b7 = buf[ps + 7U];
  uint8_t b8 = buf[ps + 8U];
  uint8_t b9 = buf[ps + 9U];
  uint8_t b10 = buf[ps + 10U];
  return
    b0 == 0x2FU && b1 == 0x61U && b2 == 0x70U && b3 == 0x69U && b4 == 0x2FU && b5 == 0x70U &&
      b6 == 0x6FU
    && b7 == 0x6CU
    && b8 == 0x69U
    && b9 == 0x63U
    && b10 == 0x79U;
}

path_result extract_path_hash(uint8_t *buf, uint32_t method_end, uint32_t header_end)
{
  uint32_t path_start = method_end;
  uint32_t path_end = find_path_end(buf, header_end, path_start);
  uint32_t path_len = path_end - path_start;
  if (!check_no_traversal(buf, path_start, path_end, path_start))
    return ((path_result){ .pr_hash = 0U, .pr_is_root = false });
  else if (!check_no_null(buf, path_end, path_start))
    return ((path_result){ .pr_hash = 0U, .pr_is_root = false });
  else if (is_root_path(buf, path_start, path_end))
    return ((path_result){ .pr_hash = 0U, .pr_is_root = true });
  else if (path_len == 10U)
    if (is_path_login(buf, path_start))
      return ((path_result){ .pr_hash = 0x11111111U, .pr_is_root = false });
    else
      return ((path_result){ .pr_hash = 0U, .pr_is_root = false });
  else if (path_len == 11U)
    if (is_path_logout(buf, path_start))
      return ((path_result){ .pr_hash = 0x22222222U, .pr_is_root = false });
    else if (is_path_status(buf, path_start))
      return ((path_result){ .pr_hash = 0x33333333U, .pr_is_root = false });
    else if (is_path_policy(buf, path_start))
      return ((path_result){ .pr_hash = 0x44444444U, .pr_is_root = false });
    else
      return ((path_result){ .pr_hash = 0U, .pr_is_root = false });
  else
    return ((path_result){ .pr_hash = 0U, .pr_is_root = false });
}

