/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: krml -skip-linking -skip-compilation -tmpdir extracted -bundle HTTP.Extract.Types=HTTP.Extract.Types -bundle HTTP.Extract.Scan=HTTP.Extract.Scan -bundle HTTP.Extract.Method=HTTP.Extract.Method -bundle HTTP.Extract.Path=HTTP.Extract.Path -bundle HTTP.Extract.Header=HTTP.Extract.Header -bundle HTTP.Extract.Bearer=HTTP.Extract.Bearer -bundle HTTP.Extract.Complete=HTTP.Extract.Complete -bundle IPC.Extract=IPC.Extract -no-prefix HTTP.Extract.Types -no-prefix HTTP.Extract.Scan -no-prefix HTTP.Extract.Method -no-prefix HTTP.Extract.Path -no-prefix HTTP.Extract.Header -no-prefix HTTP.Extract.Bearer -no-prefix HTTP.Extract.Complete -no-prefix IPC.Extract .extract/out.krml
  F* version: <unknown>
  KaRaMeL version: <unknown>
 */

#ifndef HTTP_Extract_Path_H
#define HTTP_Extract_Path_H

#include "krmllib.h"

#include "HTTP_Extract_Types.h"

uint32_t find_path_end(uint8_t *buf, uint32_t limit, uint32_t i);

bool check_no_traversal(uint8_t *buf, uint32_t path_start, uint32_t path_end, uint32_t i);

bool check_no_null(uint8_t *buf, uint32_t path_end, uint32_t i);

bool is_root_path(uint8_t *buf, uint32_t path_start, uint32_t path_end);

bool is_path_login(uint8_t *buf, uint32_t ps);

bool is_path_logout(uint8_t *buf, uint32_t ps);

bool is_path_status(uint8_t *buf, uint32_t ps);

bool is_path_policy(uint8_t *buf, uint32_t ps);

path_result extract_path_hash(uint8_t *buf, uint32_t method_end, uint32_t header_end);


#define HTTP_Extract_Path_H_DEFINED
#endif /* HTTP_Extract_Path_H */
