/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: krml -skip-linking -skip-compilation -tmpdir extracted -bundle HTTP.Extract.Types=HTTP.Extract.Types -bundle HTTP.Extract.Scan=HTTP.Extract.Scan -bundle HTTP.Extract.Method=HTTP.Extract.Method -bundle HTTP.Extract.Path=HTTP.Extract.Path -bundle HTTP.Extract.Header=HTTP.Extract.Header -bundle HTTP.Extract.Bearer=HTTP.Extract.Bearer -bundle HTTP.Extract.Complete=HTTP.Extract.Complete -bundle IPC.Extract=IPC.Extract -no-prefix HTTP.Extract.Types -no-prefix HTTP.Extract.Scan -no-prefix HTTP.Extract.Method -no-prefix HTTP.Extract.Path -no-prefix HTTP.Extract.Header -no-prefix HTTP.Extract.Bearer -no-prefix HTTP.Extract.Complete -no-prefix IPC.Extract .extract/out.krml
  F* version: <unknown>
  KaRaMeL version: <unknown>
 */

#include "HTTP_Extract_Bearer.h"

bool check_auth_bearer(uint8_t *buf, uint32_t h)
{
  uint8_t b0 = buf[h];
  uint8_t b1 = buf[h + 1U];
  uint8_t b2 = buf[h + 2U];
  uint8_t b3 = buf[h + 3U];
  uint8_t b4 = buf[h + 4U];
  uint8_t b5 = buf[h + 5U];
  uint8_t b6 = buf[h + 6U];
  uint8_t b7 = buf[h + 7U];
  uint8_t b8 = buf[h + 8U];
  uint8_t b9 = buf[h + 9U];
  uint8_t b10 = buf[h + 10U];
  uint8_t b11 = buf[h + 11U];
  uint8_t b12 = buf[h + 12U];
  uint8_t b13 = buf[h + 13U];
  uint8_t b14 = buf[h + 14U];
  uint8_t b15 = buf[h + 15U];
  uint8_t b16 = buf[h + 16U];
  uint8_t b17 = buf[h + 17U];
  uint8_t b18 = buf[h + 18U];
  uint8_t b19 = buf[h + 19U];
  uint8_t b20 = buf[h + 20U];
  uint8_t b21 = buf[h + 21U];
  return
    b0 == 0x41U && b1 == 0x75U && b2 == 0x74U && b3 == 0x68U && b4 == 0x6FU && b5 == 0x72U &&
      b6 == 0x69U
    && b7 == 0x7AU
    && b8 == 0x61U
    && b9 == 0x74U
    && b10 == 0x69U
    && b11 == 0x6FU
    && b12 == 0x6EU
    && b13 == 0x3AU
    && b14 == 0x20U
    && b15 == 0x42U
    && b16 == 0x65U
    && b17 == 0x61U
    && b18 == 0x72U
    && b19 == 0x65U
    && b20 == 0x72U
    && b21 == 0x20U;
}

uint8_t
copy_token_bytes(uint8_t *buf, uint8_t *out, uint32_t header_end, uint32_t pos, uint32_t i)
{
  if (i == 128U)
    return 128U;
  else if (pos == header_end)
    return (uint8_t)i;
  else
  {
    uint8_t b = buf[pos];
    if (b == 0x0DU)
      return (uint8_t)i;
    else
    {
      out[i] = b;
      return copy_token_bytes(buf, out, header_end, pos + 1U, i + 1U);
    }
  }
}

uint8_t scan_for_bearer(uint8_t *buf, uint32_t header_end, uint8_t *out, uint32_t i)
{
  if (header_end - i < 24U)
    return 0U;
  else
  {
    uint8_t b0 = buf[i];
    uint8_t b1 = buf[i + 1U];
    if (b0 == 0x0DU && b1 == 0x0AU)
    {
      uint32_t h = i + 2U;
      if (h + 22U <= header_end)
      {
        bool is_bearer = check_auth_bearer(buf, h);
        if (is_bearer)
        {
          uint32_t token_start = h + 22U;
          return copy_token_bytes(buf, out, header_end, token_start, 0U);
        }
        else
          return scan_for_bearer(buf, header_end, out, i + 1U);
      }
      else
        return 0U;
    }
    else
      return scan_for_bearer(buf, header_end, out, i + 1U);
  }
}

uint8_t extract_bearer_token(uint8_t *buf, uint32_t header_end, uint8_t *out_token)
{
  return scan_for_bearer(buf, header_end, out_token, 0U);
}

