/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: krml -skip-linking -skip-compilation -tmpdir extracted -bundle HTTP.Extract.Types=HTTP.Extract.Types -bundle HTTP.Extract.Scan=HTTP.Extract.Scan -bundle HTTP.Extract.Method=HTTP.Extract.Method -bundle HTTP.Extract.Path=HTTP.Extract.Path -bundle HTTP.Extract.Header=HTTP.Extract.Header -bundle HTTP.Extract.Bearer=HTTP.Extract.Bearer -bundle HTTP.Extract.Complete=HTTP.Extract.Complete -bundle IPC.Extract=IPC.Extract -no-prefix HTTP.Extract.Types -no-prefix HTTP.Extract.Scan -no-prefix HTTP.Extract.Method -no-prefix HTTP.Extract.Path -no-prefix HTTP.Extract.Header -no-prefix HTTP.Extract.Bearer -no-prefix HTTP.Extract.Complete -no-prefix IPC.Extract .extract/out.krml
  F* version: <unknown>
  KaRaMeL version: <unknown>
 */

#include "HTTP_Extract_Types.h"

uint8_t method_get = 1U;

uint8_t method_post = 2U;

uint8_t method_put = 3U;

uint32_t path_login = 0x11111111U;

uint32_t path_logout = 0x22222222U;

uint32_t path_status = 0x33333333U;

uint32_t path_policy = 0x44444444U;

uint32_t secparams_header_size = 175U;

uint32_t max_inline_body = 1361U;

uint32_t off_rate_count = 0U;

uint32_t off_path_hash = 1U;

uint32_t off_method = 5U;

uint32_t off_role = 6U;

uint32_t off_scope_lo = 7U;

uint32_t off_scope_hi = 8U;

uint32_t off_subject_id_len = 9U;

uint32_t off_subject_id = 10U;

uint32_t subject_id_max = 32U;

uint32_t off_token_len = 42U;

uint32_t off_token = 43U;

uint32_t off_body_len = 171U;

uint32_t auth_token_max = 128U;

uint8_t extract_ok = 0U;

uint8_t extract_incomplete = 1U;

uint8_t extract_malformed = 2U;

uint8_t extract_body_too_large = 3U;

uint8_t extract_path_traversal = 4U;

uint8_t extract_method_unknown = 5U;

