/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: krml -skip-linking -skip-compilation -tmpdir extracted -bundle HTTP.Extract.Types=HTTP.Extract.Types -bundle HTTP.Extract.Scan=HTTP.Extract.Scan -bundle HTTP.Extract.Method=HTTP.Extract.Method -bundle HTTP.Extract.Path=HTTP.Extract.Path -bundle HTTP.Extract.Header=HTTP.Extract.Header -bundle HTTP.Extract.Bearer=HTTP.Extract.Bearer -bundle HTTP.Extract.Complete=HTTP.Extract.Complete -bundle IPC.Extract=IPC.Extract -no-prefix HTTP.Extract.Types -no-prefix HTTP.Extract.Scan -no-prefix HTTP.Extract.Method -no-prefix HTTP.Extract.Path -no-prefix HTTP.Extract.Header -no-prefix HTTP.Extract.Bearer -no-prefix HTTP.Extract.Complete -no-prefix IPC.Extract .extract/out.krml
  F* version: <unknown>
  KaRaMeL version: <unknown>
 */

#ifndef IPC_Extract_H
#define IPC_Extract_H

#include "krmllib.h"

void copy_subject_bytes(uint8_t *out_buf, uint8_t *auth_buf, uint32_t len, uint32_t i);

void populate_auth_fields(uint8_t *out_buf, uint8_t *auth_buf);

void populate_rate_field(uint8_t *out_buf, uint8_t rate_val);


#define IPC_Extract_H_DEFINED
#endif /* IPC_Extract_H */
