/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: krml -skip-linking -skip-compilation -tmpdir extracted -bundle HTTP.Extract.Types=HTTP.Extract.Types -bundle HTTP.Extract.Scan=HTTP.Extract.Scan -bundle HTTP.Extract.Method=HTTP.Extract.Method -bundle HTTP.Extract.Path=HTTP.Extract.Path -bundle HTTP.Extract.Header=HTTP.Extract.Header -bundle HTTP.Extract.Bearer=HTTP.Extract.Bearer -bundle HTTP.Extract.Complete=HTTP.Extract.Complete -no-prefix HTTP.Extract.Types -no-prefix HTTP.Extract.Scan -no-prefix HTTP.Extract.Method -no-prefix HTTP.Extract.Path -no-prefix HTTP.Extract.Header -no-prefix HTTP.Extract.Bearer -no-prefix HTTP.Extract.Complete .extract/out.krml
  F* version: <unknown>
  KaRaMeL version: <unknown>
 */

#include "HTTP_Extract_Method.h"

#include "HTTP_Extract_Types.h"

method_result parse_method(uint8_t *buf, uint32_t len)
{
  if (len < 4U)
    return ((method_result){ .mr_code = 0U, .mr_end = 0U });
  else
  {
    uint8_t b0 = buf[0U];
    uint8_t b1 = buf[1U];
    uint8_t b2 = buf[2U];
    uint8_t b3 = buf[3U];
    if (b0 == 0x47U && b1 == 0x45U && b2 == 0x54U && b3 == 0x20U)
      return ((method_result){ .mr_code = 1U, .mr_end = 4U });
    else if (b0 == 0x50U && b1 == 0x55U && b2 == 0x54U && b3 == 0x20U)
      return ((method_result){ .mr_code = 3U, .mr_end = 4U });
    else if (len >= 5U)
    {
      uint8_t b4 = buf[4U];
      if (b0 == 0x50U && b1 == 0x4FU && b2 == 0x53U && b3 == 0x54U && b4 == 0x20U)
        return ((method_result){ .mr_code = 2U, .mr_end = 5U });
      else
        return ((method_result){ .mr_code = 0U, .mr_end = 0U });
    }
    else
      return ((method_result){ .mr_code = 0U, .mr_end = 0U });
  }
}

