/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: krml -skip-linking -skip-compilation -tmpdir extracted -bundle HTTP.Extract.Types=HTTP.Extract.Types -bundle HTTP.Extract.Scan=HTTP.Extract.Scan -bundle HTTP.Extract.Method=HTTP.Extract.Method -bundle HTTP.Extract.Path=HTTP.Extract.Path -bundle HTTP.Extract.Header=HTTP.Extract.Header -bundle HTTP.Extract.Bearer=HTTP.Extract.Bearer -bundle HTTP.Extract.Complete=HTTP.Extract.Complete -no-prefix HTTP.Extract.Types -no-prefix HTTP.Extract.Scan -no-prefix HTTP.Extract.Method -no-prefix HTTP.Extract.Path -no-prefix HTTP.Extract.Header -no-prefix HTTP.Extract.Bearer -no-prefix HTTP.Extract.Complete .extract/out.krml
  F* version: <unknown>
  KaRaMeL version: <unknown>
 */

#ifndef HTTP_Extract_Complete_H
#define HTTP_Extract_Complete_H

#include "krmllib.h"

void fill_zero(uint8_t *buf, uint32_t i, uint32_t stop);

void write_u32_le(uint8_t *buf, uint32_t off, uint32_t v);

void
copy_bytes(
  uint8_t *dst,
  uint8_t *src,
  uint32_t dst_off,
  uint32_t src_off,
  uint32_t len,
  uint32_t i
);

uint8_t
extract_security_params(
  uint8_t *http_buf,
  uint32_t http_len,
  uint8_t *out_buf,
  uint32_t *out_len
);


#define HTTP_Extract_Complete_H_DEFINED
#endif /* HTTP_Extract_Complete_H */
