/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: krml -skip-linking -skip-compilation -tmpdir extracted -bundle HTTP.Extract.Types=HTTP.Extract.Types -bundle HTTP.Extract.Scan=HTTP.Extract.Scan -bundle HTTP.Extract.Method=HTTP.Extract.Method -bundle HTTP.Extract.Path=HTTP.Extract.Path -bundle HTTP.Extract.Header=HTTP.Extract.Header -bundle HTTP.Extract.Bearer=HTTP.Extract.Bearer -bundle HTTP.Extract.Complete=HTTP.Extract.Complete -no-prefix HTTP.Extract.Types -no-prefix HTTP.Extract.Scan -no-prefix HTTP.Extract.Method -no-prefix HTTP.Extract.Path -no-prefix HTTP.Extract.Header -no-prefix HTTP.Extract.Bearer -no-prefix HTTP.Extract.Complete .extract/out.krml
  F* version: <unknown>
  KaRaMeL version: <unknown>
 */

#include "HTTP_Extract_Scan.h"

uint8_t cr = 0x0DU;

uint8_t lf = 0x0AU;

uint32_t scan_loop(uint8_t *buf, uint32_t len, uint32_t i)
{
  if (i > len - 4U)
    return len;
  else
  {
    uint8_t b0 = buf[i];
    uint8_t b1 = buf[i + 1U];
    uint8_t b2 = buf[i + 2U];
    uint8_t b3 = buf[i + 3U];
    if (b0 == 0x0DU && b1 == 0x0AU && b2 == 0x0DU && b3 == 0x0AU)
      return i;
    else
      return scan_loop(buf, len, i + 1U);
  }
}

uint32_t find_header_end(uint8_t *buf, uint32_t len)
{
  if (len < 4U)
    return len;
  else
    return scan_loop(buf, len, 0U);
}

