/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: krml -skip-linking -skip-compilation -tmpdir extracted -bundle HTTP.Extract.Types=HTTP.Extract.Types -bundle HTTP.Extract.Scan=HTTP.Extract.Scan -bundle HTTP.Extract.Method=HTTP.Extract.Method -bundle HTTP.Extract.Path=HTTP.Extract.Path -bundle HTTP.Extract.Header=HTTP.Extract.Header -bundle HTTP.Extract.Bearer=HTTP.Extract.Bearer -bundle HTTP.Extract.Complete=HTTP.Extract.Complete -no-prefix HTTP.Extract.Types -no-prefix HTTP.Extract.Scan -no-prefix HTTP.Extract.Method -no-prefix HTTP.Extract.Path -no-prefix HTTP.Extract.Header -no-prefix HTTP.Extract.Bearer -no-prefix HTTP.Extract.Complete .extract/out.krml
  F* version: <unknown>
  KaRaMeL version: <unknown>
 */

#ifndef HTTP_Extract_Header_H
#define HTTP_Extract_Header_H

#include "krmllib.h"

uint32_t parse_digits(uint8_t *buf, uint32_t header_end, uint32_t j, uint32_t acc);

uint32_t skip_spaces(uint8_t *buf, uint32_t header_end, uint32_t j);

bool check_content_length_upper(uint8_t *buf, uint32_t h);

bool check_content_length_lower(uint8_t *buf, uint32_t h);

uint32_t scan_for_content_length(uint8_t *buf, uint32_t header_end, uint32_t i);

uint32_t parse_content_length(uint8_t *buf, uint32_t header_end);


#define HTTP_Extract_Header_H_DEFINED
#endif /* HTTP_Extract_Header_H */
