/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: krml -skip-linking -skip-compilation -tmpdir extracted -bundle HTTP.Extract.Types=HTTP.Extract.Types -bundle HTTP.Extract.Scan=HTTP.Extract.Scan -bundle HTTP.Extract.Method=HTTP.Extract.Method -bundle HTTP.Extract.Path=HTTP.Extract.Path -bundle HTTP.Extract.Header=HTTP.Extract.Header -bundle HTTP.Extract.Bearer=HTTP.Extract.Bearer -bundle HTTP.Extract.Complete=HTTP.Extract.Complete -no-prefix HTTP.Extract.Types -no-prefix HTTP.Extract.Scan -no-prefix HTTP.Extract.Method -no-prefix HTTP.Extract.Path -no-prefix HTTP.Extract.Header -no-prefix HTTP.Extract.Bearer -no-prefix HTTP.Extract.Complete .extract/out.krml
  F* version: <unknown>
  KaRaMeL version: <unknown>
 */

#ifndef HTTP_Extract_Bearer_H
#define HTTP_Extract_Bearer_H

#include "krmllib.h"

bool check_auth_bearer(uint8_t *buf, uint32_t h);

uint8_t
copy_token_bytes(uint8_t *buf, uint8_t *out, uint32_t header_end, uint32_t pos, uint32_t i);

uint8_t scan_for_bearer(uint8_t *buf, uint32_t header_end, uint8_t *out, uint32_t i);

uint8_t extract_bearer_token(uint8_t *buf, uint32_t header_end, uint8_t *out_token);


#define HTTP_Extract_Bearer_H_DEFINED
#endif /* HTTP_Extract_Bearer_H */
