/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: krml -skip-linking -skip-compilation -tmpdir extracted -bundle HTTP.Extract.Types=HTTP.Extract.Types -bundle HTTP.Extract.Scan=HTTP.Extract.Scan -bundle HTTP.Extract.Method=HTTP.Extract.Method -bundle HTTP.Extract.Path=HTTP.Extract.Path -bundle HTTP.Extract.Header=HTTP.Extract.Header -bundle HTTP.Extract.Bearer=HTTP.Extract.Bearer -bundle HTTP.Extract.Complete=HTTP.Extract.Complete -no-prefix HTTP.Extract.Types -no-prefix HTTP.Extract.Scan -no-prefix HTTP.Extract.Method -no-prefix HTTP.Extract.Path -no-prefix HTTP.Extract.Header -no-prefix HTTP.Extract.Bearer -no-prefix HTTP.Extract.Complete .extract/out.krml
  F* version: <unknown>
  KaRaMeL version: <unknown>
 */

#include "HTTP_Extract_Complete.h"

#include "HTTP_Extract_Types.h"
#include "HTTP_Extract_Scan.h"
#include "HTTP_Extract_Path.h"
#include "HTTP_Extract_Method.h"
#include "HTTP_Extract_Header.h"
#include "HTTP_Extract_Bearer.h"

void fill_zero(uint8_t *buf, uint32_t i, uint32_t stop)
{
  if (!(i == stop))
  {
    buf[i] = 0U;
    fill_zero(buf, i + 1U, stop);
  }
}

void write_u32_le(uint8_t *buf, uint32_t off, uint32_t v)
{
  buf[off] = (uint8_t)v;
  buf[off + 1U] = (uint8_t)(v >> 8U);
  buf[off + 2U] = (uint8_t)(v >> 16U);
  buf[off + 3U] = (uint8_t)(v >> 24U);
}

void
copy_bytes(
  uint8_t *dst,
  uint8_t *src,
  uint32_t dst_off,
  uint32_t src_off,
  uint32_t len,
  uint32_t i
)
{
  if (!(i == len))
  {
    uint8_t b = src[src_off + i];
    dst[dst_off + i] = b;
    copy_bytes(dst, src, dst_off, src_off, len, i + 1U);
  }
}

uint8_t
extract_security_params(
  uint8_t *http_buf,
  uint32_t http_len,
  uint8_t *out_buf,
  uint32_t *out_len
)
{
  uint32_t hdr_end = find_header_end(http_buf, http_len);
  if (hdr_end == http_len)
  {
    out_len[0U] = 0U;
    return 1U;
  }
  else
  {
    method_result mr = parse_method(http_buf, http_len);
    if (mr.mr_code == 0U)
    {
      out_len[0U] = 0U;
      return 5U;
    }
    else if (mr.mr_end > hdr_end)
    {
      out_len[0U] = 0U;
      return 2U;
    }
    else
    {
      path_result pr = extract_path_hash(http_buf, mr.mr_end, hdr_end);
      if (pr.pr_is_root)
      {
        fill_zero(out_buf, 0U, 175U);
        out_buf[5U] = mr.mr_code;
        out_len[0U] = 175U;
        return 0U;
      }
      else if (pr.pr_hash == 0U)
      {
        uint32_t path_start = mr.mr_end;
        uint32_t path_end = find_path_end(http_buf, hdr_end, path_start);
        bool trav_safe = check_no_traversal(http_buf, path_start, path_end, path_start);
        out_len[0U] = 0U;
        if (!trav_safe)
          return 4U;
        else
          return 2U;
      }
      else
      {
        uint32_t content_length = parse_content_length(http_buf, hdr_end);
        if (content_length > 1361U)
        {
          out_len[0U] = 0U;
          return 3U;
        }
        else
        {
          uint32_t body_start = hdr_end + 4U;
          uint32_t available_body;
          if (http_len > body_start)
            available_body = http_len - body_start;
          else
            available_body = 0U;
          if (content_length > 0U && available_body < content_length)
          {
            out_len[0U] = 0U;
            return 1U;
          }
          else
          {
            uint32_t body_len;
            if (content_length > 0U)
              body_len = content_length;
            else
              body_len = 0U;
            fill_zero(out_buf, 0U, 175U);
            write_u32_le(out_buf, 1U, pr.pr_hash);
            out_buf[5U] = mr.mr_code;
            uint8_t *token_sub = out_buf + 43U;
            uint8_t tklen = extract_bearer_token(http_buf, hdr_end, token_sub);
            out_buf[42U] = tklen;
            write_u32_le(out_buf, 171U, body_len);
            if (body_len > 0U)
              copy_bytes(out_buf, http_buf, 175U, body_start, body_len, 0U);
            out_len[0U] = 175U + body_len;
            return 0U;
          }
        }
      }
    }
  }
}

