/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: krml -skip-linking -skip-compilation -tmpdir extracted -bundle HTTP.Extract.Types=HTTP.Extract.Types -bundle HTTP.Extract.Scan=HTTP.Extract.Scan -bundle HTTP.Extract.Method=HTTP.Extract.Method -bundle HTTP.Extract.Path=HTTP.Extract.Path -bundle HTTP.Extract.Header=HTTP.Extract.Header -bundle HTTP.Extract.Bearer=HTTP.Extract.Bearer -bundle HTTP.Extract.Complete=HTTP.Extract.Complete -bundle IPC.Extract=IPC.Extract -no-prefix HTTP.Extract.Types -no-prefix HTTP.Extract.Scan -no-prefix HTTP.Extract.Method -no-prefix HTTP.Extract.Path -no-prefix HTTP.Extract.Header -no-prefix HTTP.Extract.Bearer -no-prefix HTTP.Extract.Complete -no-prefix IPC.Extract .extract/out.krml
  F* version: <unknown>
  KaRaMeL version: <unknown>
 */

#ifndef HTTP_Extract_Types_H
#define HTTP_Extract_Types_H

#include "krmllib.h"

extern uint8_t method_get;

extern uint8_t method_post;

extern uint8_t method_put;

extern uint32_t path_login;

extern uint32_t path_logout;

extern uint32_t path_status;

extern uint32_t path_policy;

extern uint32_t secparams_header_size;

extern uint32_t max_inline_body;

extern uint32_t off_rate_count;

extern uint32_t off_path_hash;

extern uint32_t off_method;

extern uint32_t off_role;

extern uint32_t off_scope_lo;

extern uint32_t off_scope_hi;

extern uint32_t off_subject_id_len;

extern uint32_t off_subject_id;

extern uint32_t subject_id_max;

extern uint32_t off_token_len;

extern uint32_t off_token;

extern uint32_t off_body_len;

extern uint32_t auth_token_max;

extern uint8_t extract_ok;

extern uint8_t extract_incomplete;

extern uint8_t extract_malformed;

extern uint8_t extract_body_too_large;

extern uint8_t extract_path_traversal;

extern uint8_t extract_method_unknown;

typedef struct method_result_s
{
  uint8_t mr_code;
  uint32_t mr_end;
}
method_result;

typedef struct path_result_s
{
  uint32_t pr_hash;
  bool pr_is_root;
}
path_result;


#define HTTP_Extract_Types_H_DEFINED
#endif /* HTTP_Extract_Types_H */
