/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: krml -skip-linking -skip-compilation -tmpdir extracted -bundle HTTP.Extract.Types=HTTP.Extract.Types -bundle HTTP.Extract.Scan=HTTP.Extract.Scan -bundle HTTP.Extract.Method=HTTP.Extract.Method -bundle HTTP.Extract.Path=HTTP.Extract.Path -bundle HTTP.Extract.Header=HTTP.Extract.Header -bundle HTTP.Extract.Bearer=HTTP.Extract.Bearer -bundle HTTP.Extract.Complete=HTTP.Extract.Complete -bundle IPC.Extract=IPC.Extract -no-prefix HTTP.Extract.Types -no-prefix HTTP.Extract.Scan -no-prefix HTTP.Extract.Method -no-prefix HTTP.Extract.Path -no-prefix HTTP.Extract.Header -no-prefix HTTP.Extract.Bearer -no-prefix HTTP.Extract.Complete -no-prefix IPC.Extract .extract/out.krml
  F* version: <unknown>
  KaRaMeL version: <unknown>
 */

#include "IPC_Extract.h"

void copy_subject_bytes(uint8_t *out_buf, uint8_t *auth_buf, uint32_t len, uint32_t i)
{
  if (!(i == len))
  {
    uint8_t b = auth_buf[5U + i];
    out_buf[10U + i] = b;
    copy_subject_bytes(out_buf, auth_buf, len, i + 1U);
  }
}

void populate_auth_fields(uint8_t *out_buf, uint8_t *auth_buf)
{
  uint8_t raw_role = auth_buf[1U];
  uint8_t role;
  if (raw_role > 2U)
    role = 2U;
  else
    role = raw_role;
  uint8_t scope_lo = auth_buf[2U];
  uint8_t scope_hi = auth_buf[3U];
  uint8_t raw_sub_len = auth_buf[4U];
  uint8_t sub_len;
  if (raw_sub_len > 32U)
    sub_len = 32U;
  else
    sub_len = raw_sub_len;
  uint32_t sub_len32 = (uint32_t)sub_len;
  copy_subject_bytes(out_buf, auth_buf, sub_len32, 0U);
  out_buf[6U] = role;
  out_buf[7U] = scope_lo;
  out_buf[8U] = scope_hi;
  out_buf[9U] = sub_len;
}

void populate_rate_field(uint8_t *out_buf, uint8_t rate_val)
{
  out_buf[0U] = rate_val;
}

