#!/usr/bin/env python3
"""
Generate EverParse 3D scale test files with M rules.

Each generated file has:
- M rule fields (6 bytes each: path_hash UINT32, method UINT8, min_role UINT8)
- 1 request field set (path_hash UINT32, method UINT8, auth_state UINT8)
- 1 rate_count UINT8 with constraint < 50
- 1 access control constraint with M disjuncts

Usage: python3 generate_scale_test.py <M>
"""

import sys

def generate(M):
    name = f"ScaleTest{M}"
    filename = f"{name}.3d"

    lines = []
    lines.append(f"/* EverParse Scale Test: {M} rules */")
    lines.append("")
    lines.append("#define MAX_RATE 50")
    lines.append("#define DEAD_HASH 0xDEADDEADul")
    lines.append("")
    lines.append("entrypoint")
    lines.append(f"typedef struct _{name}")
    lines.append("{")

    # Rule fields
    for i in range(M):
        lines.append(f"    /* Rule {i} */")
        lines.append(f"    UINT32 r{i}_path_hash;")
        lines.append(f"    UINT8  r{i}_method;")
        lines.append(f"    UINT8  r{i}_min_role;")
        lines.append("")

    # Request fields
    lines.append("    /* Request */")
    lines.append("    UINT32 req_path_hash;")
    lines.append("    UINT8  req_method;")
    lines.append("    UINT8  auth_state;")
    lines.append("")

    # Rate count with constraint
    lines.append("    /* Rate limit (CNF) */")
    lines.append("    UINT8  rate_count;")
    lines.append("    UINT8  _rate_ok { rate_count < MAX_RATE };")
    lines.append("")

    # Access control constraint with M disjuncts
    lines.append("    /* Access control (DNF) */")
    lines.append("    UINT8  _access_ok")
    lines.append("    {")

    disjuncts = []
    for i in range(M):
        d = (f"        (r{i}_path_hash == req_path_hash && "
             f"r{i}_method == req_method && "
             f"auth_state >= r{i}_min_role)")
        disjuncts.append(d)

    lines.append(" ||\n".join(disjuncts))
    lines.append("    };")
    lines.append(f"}} {name};")
    lines.append("")

    with open(filename, "w") as f:
        f.write("\n".join(lines))

    print(f"Generated {filename} ({M} rules)")

    # Also generate functional test harness
    generate_harness(M, name)

def generate_harness(M, name):
    """Generate a minimal C test harness for the scale test."""
    # Module name casing: EverParse preserves PascalCase for wrapper functions.
    # ScaleTest4 -> ScaleTest4CheckScaleTest4 (confirmed empirically)
    module_name = name

    # Buffer size: M*6 (rules) + 6 (request) + 1 (rate_count) + 1 (_rate_ok) + 1 (_access_ok)
    buf_size = M * 6 + 6 + 1 + 1 + 1

    harness = f"""/*
 * Scale Test Functional Harness: M={M}
 * Auto-generated by generate_scale_test.py
 *
 * Test 1: rule_0 matches a known request -> ACCEPT
 * Test 2: all rules DEAD_HASH -> REJECT
 */

#include <stdio.h>
#include <string.h>
#include <stdint.h>
#include "{name}Wrapper.h"

#define HASH_STATUS  0xAAAAAAAAu
#define DEAD_HASH    0xDEADDEADu
#define METHOD_GET   1
#define ROLE_OPERATOR 1

#define BUF_SIZE {buf_size}

void {name}EverParseError(
    const char *struct_name,
    const char *field_name,
    const char *reason)
{{
    (void)struct_name; (void)field_name; (void)reason;
}}

static void write_u32(uint8_t *buf, int offset, uint32_t val)
{{
    buf[offset + 0] = (val >>  0) & 0xFF;
    buf[offset + 1] = (val >>  8) & 0xFF;
    buf[offset + 2] = (val >> 16) & 0xFF;
    buf[offset + 3] = (val >> 24) & 0xFF;
}}

static void write_rule(uint8_t *buf, int offset,
                       uint32_t path_hash, uint8_t method, uint8_t min_role)
{{
    write_u32(buf, offset, path_hash);
    buf[offset + 4] = method;
    buf[offset + 5] = min_role;
}}

int main(void)
{{
    uint8_t buf[BUF_SIZE];
    int passed = 0, total = 0;
    BOOLEAN result;

    printf("=== Scale Test M={M} ===\\n");

    /* Test 1: rule_0 matches -> ACCEPT */
    memset(buf, 0, BUF_SIZE);
    /* Rule 0: GET /status requires OPERATOR */
    write_rule(buf, 0, HASH_STATUS, METHOD_GET, ROLE_OPERATOR);
    /* Rules 1..{M-1}: DEAD_HASH (unused) */
    for (int i = 1; i < {M}; i++) {{
        write_rule(buf, i * 6, DEAD_HASH, 0, 0);
    }}
    /* Request: GET /status as OPERATOR */
    int req_off = {M} * 6;
    write_u32(buf, req_off, HASH_STATUS);
    buf[req_off + 4] = METHOD_GET;
    buf[req_off + 5] = ROLE_OPERATOR;  /* auth_state */
    /* rate_count = 5 */
    buf[req_off + 6] = 5;
    /* _rate_ok and _access_ok check bytes */
    buf[req_off + 7] = 0;
    buf[req_off + 8] = 0;

    /* Call EverParse wrapper */
    result = {module_name}Check{name}(buf, BUF_SIZE);
    total++;
    if (result) {{
        printf("  PASS: Test 1 (rule_0 matches -> ACCEPT)\\n");
        passed++;
    }} else {{
        printf("  FAIL: Test 1 (rule_0 matches -> expected ACCEPT, got REJECT)\\n");
    }}

    /* Test 2: all rules DEAD_HASH -> REJECT */
    memset(buf, 0, BUF_SIZE);
    for (int i = 0; i < {M}; i++) {{
        write_rule(buf, i * 6, DEAD_HASH, 0, 0);
    }}
    req_off = {M} * 6;
    write_u32(buf, req_off, HASH_STATUS);
    buf[req_off + 4] = METHOD_GET;
    buf[req_off + 5] = ROLE_OPERATOR;
    buf[req_off + 6] = 5;
    buf[req_off + 7] = 0;
    buf[req_off + 8] = 0;

    result = {module_name}Check{name}(buf, BUF_SIZE);
    total++;
    if (!result) {{
        printf("  PASS: Test 2 (all DEAD_HASH -> REJECT)\\n");
        passed++;
    }} else {{
        printf("  FAIL: Test 2 (all DEAD_HASH -> expected REJECT, got ACCEPT)\\n");
    }}

    printf("\\nResults: %d/%d passed\\n", passed, total);
    return (passed == total) ? 0 : 1;
}}
"""

    harness_file = f"scale_func_test_{M}.c"
    with open(harness_file, "w") as f:
        f.write(harness)
    print(f"Generated {harness_file}")

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print(f"Usage: {sys.argv[0]} <M>")
        sys.exit(1)
    M = int(sys.argv[1])
    generate(M)
